### ISSUE TITLE
file sizes?!?

### ISSUE THREAD

**Issue by jedie** [pmp-p/micropython-ports-wasm#1]
I'm came from: https://github.com/micropython/micropython/issues/888

PyPy.js had the problem that it is simply too big: The loading times are simply too long for practical use. See: https://github.com/pypyjs/pypyjs/issues/196

What's the requestes size here for a complete loaded python interpreter?

**Comment by pmp-p** [comment]
it loads instantly the whole test folder is 1.8MiB with all modules listed in screenshot
no way pypy or cpython can beat micropython on loading speeds

**Comment by jedie** [comment]
That sounds pretty good... Meanwhile many JavaScript frameworks have become bigger...

Please look at: https://github.com/pypyjs/pypyjs-examples

Is everything already there so that you can create the examples with "micropython-ports-wasm" ?

btw. the name "micropython-ports-wasm" is a little long ;)

**Comment by pmp-p** [comment]
no you need to checkout micropython-master , because `micropython-ports-wasm` matches  `micropython/ports/wasm` folder, that's not a standalone micropython , micropython hosts his targets in its "ports" folder and the makefile commands are relative to the parent folders.
about examples, i just don't know yet what that port is capable of. Feel free to try :)

**Comment by pmp-p** [comment]
Maybe later when dom and c/c++ modules dynamic linking is in, there are still bugs in micropython master ( unrelated to the numerous ones in this port ) and i have an intermediate patching stage to establish to fully support asyncio.

This port is an early experiment with no licensing, do not expect anything stable for weeks even if it *looks* ok. i'm also waiting for @brion and his libffi basic support https://github.com/brion/libffi/tree/emscripten-work

**Comment by pmp-p** [comment]
maybe ask for compiled version here https://github.com/micropython/micropython/tree/master/ports/javascript . As i won't release until uasyncio/dom and the bridge sockets->websockets are really tested.
